
version: "3"
services:
  api:
    image: wellingtondevops/api-ts
    ports:
      - "5000:3050"
    links:
      - link-db
  link-db:
    image: tutum/mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
      - MONGODB_PASS="5elsT6KtjrqV"